---
- name: Check if DH param already exists
  stat:
    path: "{{ dhparam_path }}"
  register: dhparam_file
  become: true

- name: Generate Diffie-Hellman params
  command: "openssl dhparam -out {{ dhparam_path }} {{ dhparam_size }}"
  when: dhparam_file.stat.exists == False or DHPARAM_GENERATE_FORCE
  become: true
